version: '2.1'
services: 
    angular-service:
      container_name: ng-employee-and-department  
      build:
        context: .
        dockerfile: ./Dockerfile
      ports: 
        - '80:80' 
      extra_hosts:
        - "host.docker.internal:host-gateway"
#      networks:
#        employee-and-department-network:
#          aliases:
#            - webapp

#networks:
#  employee-and-department-network:
#    external:
#      name: employee-and-department-network
